# Generated by Django 4.2 on 2025-12-03 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('well_number', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Номер скважины')),
                ('field', models.CharField(max_length=100, verbose_name='Месторождение')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Широта')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Долгота')),
                ('depth', models.FloatField(verbose_name='Глубина')),
                ('status', models.CharField(choices=[('active', 'Активная'), ('inactive', 'Неактивная'), ('maintenance', 'На обслуживании'), ('emergency', 'Аварийная')], default='active', max_length=20, verbose_name='Статус скважины')),
                ('current_pressure', models.FloatField(blank=True, null=True, verbose_name='Текущее давление, атм')),
                ('measured_flow_rate', models.FloatField(blank=True, help_text='Фактический замер из телеметрии', null=True, verbose_name='Измеренный дебит, м³/сут')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='Температура пласта, °C')),
                ('last_data_update', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление данных')),
            ],
            options={
                'verbose_name': 'Скважина',
                'verbose_name_plural': 'Скважины',
                'ordering': ['well_number'],
            },
        ),
    ]
